"""Slash command: /qrcode — generate a branded GSA NJIT QR code."""

import io
import logging
from typing import Optional

import discord
from discord import app_commands
from discord.ext import commands

from bot.services.qr import MAX_QR_INPUT, build_pair

logger = logging.getLogger(__name__)


class QRCodeCog(commands.Cog, name="QRCode"):
    """Handles /qrcode — generates branded GSA NJIT QR codes."""

    def __init__(self, bot: commands.Bot) -> None:
        self.bot = bot

    @app_commands.command(
        name="qrcode",
        description="Generate a branded GSA NJIT QR code for any URL or text.",
    )
    @app_commands.describe(
        content="The URL or text to encode (max 500 characters).",
        style="Color style — Black & White (default) or Red & White.",
    )
    @app_commands.choices(style=[
        app_commands.Choice(name="Black & White (default)", value="black"),
        app_commands.Choice(name="Red & White", value="red"),
    ])
    async def qrcode(
        self,
        interaction: discord.Interaction,
        content: str,
        style: Optional[app_commands.Choice[str]] = None,
    ) -> None:
        content = content.strip()
        if not content:
            await interaction.response.send_message(
                "Please provide a URL or text to encode.", ephemeral=True)
            return
        if len(content) > MAX_QR_INPUT:
            await interaction.response.send_message(
                f"Input too long — QR codes work best under {MAX_QR_INPUT} characters "
                f"(yours is {len(content)}).", ephemeral=True)
            return
        if not self.bot.rate_limiter.is_allowed(interaction.user.id):  # type: ignore[attr-defined]
            retry = self.bot.rate_limiter.get_retry_after(interaction.user.id)  # type: ignore[attr-defined]
            await interaction.response.send_message(
                f"Slow down a bit! Try again in **{retry:.0f}s**.", ephemeral=True)
            return

        black = not (style and style.value == "red")
        style_label = "Black & White" if black else "Red & White"
        embed_color = (discord.Color.dark_gray() if black
                       else discord.Color.from_str("#CC0000"))

        await interaction.response.defer()
        try:
            branded_bytes, transparent_bytes = build_pair(content, black=black)
        except Exception:  # noqa: BLE001
            logger.exception("QR generation failed for content=%r", content[:60])
            await interaction.followup.send(
                "Something went wrong generating the QR code. Please try again.",
                ephemeral=True)
            return

        embed = discord.Embed(
            title=f"QR Code Generated — {style_label}",
            description=f"Encoded: `{content[:80]}{'...' if len(content) > 80 else ''}`",
            color=embed_color)
        embed.add_field(
            name="Files included",
            value="**qr_branded.png** — white background, GSA branding\n"
                  "**qr_transparent.png** — no background, paste onto any design",
            inline=False)
        embed.set_footer(text="GSA Gateway · paste the transparent version onto flyers & slides")

        await interaction.followup.send(
            embed=embed,
            files=[
                discord.File(io.BytesIO(branded_bytes), filename="qr_branded.png"),
                discord.File(io.BytesIO(transparent_bytes), filename="qr_transparent.png"),
            ])
        logger.info("QR code generated by %s (ID=%d) style=%s content=%r",
                    interaction.user.name, interaction.user.id, style_label, content[:60])


async def setup(bot: commands.Bot) -> None:
    await bot.add_cog(QRCodeCog(bot))
